apiVersion: integration/v1
kind: Integration
name: dockerhub
channel: alpha
version: v20200518
summary: DockerHub integration
license: Apache-2.0
homepage: https://github.com/relay-integrations/dockerhub
source: https://github.com/relay-integrations/dockerhub

description: |
  Relay GitHub integration.

owner:
  name: Puppet, Inc.
  email: relay@puppet.com
  url: https://puppet.com

tags:
- docker
- container triggers
- relay integration
