apiVersion: integration/v1
kind: Trigger
name: dockerhub-trigger-image-pushed
version: 1
summary: Docker Hub image pushed
description: |
  This trigger fires when an image is pushed to the Docker Hub registry.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/dockerhub-trigger-image-pushed
