apiVersion: integration/v1
kind: Trigger
name: dockerhub-trigger-image-pushed
version: 1
summary: Docker Hub image pushed
description: |
  This trigger fires when an image is pushed to the Docker Hub registry.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/dockerhub-trigger-image-pushed

examples:
- summary: When an image is pushed
  content:
    apiVersion: v1
    kind: Trigger
    name: image-pushed
    source:
      type: webhook
      image: relaysh/dockerhub-trigger-image-pushed
    binding:
      parameters:
        pushedAt: !Data pushedAt
        pusher: !Data pusher
        tag: !Data tag
        repoName: !Data name
